#!/usr/local/bin/escript
%% -*- erlang -*-
%%! -smp enable -name init -setcookie crdtdb

main([NodeAddress,Region, ROOT | ALL_ADDRESSES]) ->
		true = code:add_path(string:concat(ROOT, "deps/riakc/ebin")),
		true = code:add_path(string:concat(ROOT, "deps/meck/ebin")), 
		true = code:add_path(string:concat(ROOT, "deps/protobuffs/ebin")),
		true = code:add_path(string:concat(ROOT, "deps/riak_pb/ebin")),
		true = code:add_path(string:concat(ROOT, "ebin")),

		ALL = lists:map(fun(String) ->
			Id= erlang:list_to_atom(string:sub_string(String,1,string:rstr(String,":")-1)),
			Address = erlang:list_to_atom(string:sub_string(String,string:rstr(String,":")+1)),
			{Id,Address} end,ALL_ADDRESSES),
        Node = lists:append("crdtdb1@",NodeAddress),
        client_rc:start(erlang:list_to_atom(Node),list_to_atom(Region),ALL),
		halt(1).
		
