#!/usr/local/bin/escript
%% -*- erlang -*-
%%! -smp enable -name reset -setcookie crdtdb

main([NodeAddress, NUM_KEYS, INIT_VALUE, ROOT | ALL_ADDRESSES]) ->
		true = code:add_path(string:concat(ROOT, "deps/riakc/ebin")),
		true = code:add_path(string:concat(ROOT, "deps/meck/ebin")), 
		true = code:add_path(string:concat(ROOT, "deps/protobuffs/ebin")),
		true = code:add_path(string:concat(ROOT, "deps/riak_pb/ebin")),
		true = code:add_path(string:concat(ROOT, "ebin")),

		KEYS = list_to_integer(NUM_KEYS),
		VALUE = list_to_integer(INIT_VALUE),

		ALL = lists:map(fun(String) ->
        			Id= erlang:list_to_atom(string:sub_string(String,1,string:rstr(String,":")-1)),
        			Address = erlang:list_to_atom(string:sub_string(String,string:rstr(String,":")+1)),
        			{Id,Address} end,ALL_ADDRESSES),
Node = lists:append("crdtdb1@",NodeAddress),
        client_rc:reset(list_to_atom(Node),KEYS,VALUE,ALL),
        halt(1).
