#!/usr/local/bin/escript
%% -*- erlang -*-
%%! -smp enable -name reset -setcookie crdtdb

main([INIT_VALUE, BUCKET, BUCKET_TYPE, KEY, RIAK_ADDRESS, PORT, ROOT ]) ->
		true = code:add_path(string:concat(ROOT, "deps/riakc/ebin")),
		true = code:add_path(string:concat(ROOT, "deps/meck/ebin")),
		true = code:add_path(string:concat(ROOT, "deps/protobuffs/ebin")),
		true = code:add_path(string:concat(ROOT, "deps/riak_pb/ebin")),
		true = code:add_path(string:concat(ROOT, "ebin")),

		BUCKET_TERM = {list_to_binary(BUCKET_TYPE), list_to_binary(BUCKET)},

		worker_counter:reset_crdt(list_to_integer(INIT_VALUE),BUCKET_TERM,list_to_binary(KEY),RIAK_ADDRESS,list_to_integer(PORT)),
		halt(1).


