#!/usr/local/bin/escript
%% -*- erlang -*-
%%! -smp enable -sname reset

main([LOCAL_ADDRESS, INIT_VALUE, ROOT, BUCKET, BUCKET_TYPE | OTHER_SERVER_ADDRESSES]) ->
		true = code:add_path(string:concat(ROOT, "deps/riakc/ebin")),
		true = code:add_path(string:concat(ROOT, "deps/meck/ebin")), 
		true = code:add_path(string:concat(ROOT, "deps/protobuffs/ebin")),
		true = code:add_path(string:concat(ROOT, "deps/riak_pb/ebin")),
		true = code:add_path(string:concat(ROOT, "ebin")),

		V = list_to_integer(INIT_VALUE),


		BUCKET_TERM = {list_to_binary(BUCKET_TYPE), list_to_binary(BUCKET)},
		
		ALL=[{MY_ID, _} | IDS] = lists:map(fun(String) ->
			Id= string:sub_string(String,1,string:rstr(String,":")-1),
			Address = string:sub_string(String,string:rstr(String,":")+1),
			{Id,Address} end,[LOCAL_ADDRESS | OTHER_SERVER_ADDRESSES]),

		io:format("Local Id: ~p. Other Ids: ~p~n",[MY_ID, IDS]),
		io:format("ALL Addresses: ~p~n",[ALL]),

		client:reset(V,BUCKET_TERM,MY_ID,ALL),
		halt(1).
		