#!/usr/local/bin/escript
%% -*- erlang -*-
%%! -smp enable  -setcookie crdtdb


%%Addesses and ids must be acessible by indexes

main([SERVER_ADDRESS,N_THREADS, ROOT, OUTPUT_DIR, REGION]) ->
		true = code:add_path(string:concat(ROOT, "deps/riakc/ebin")),
		true = code:add_path(string:concat(ROOT, "deps/meck/ebin")), 
		true = code:add_path(string:concat(ROOT, "deps/protobuffs/ebin")),
		true = code:add_path(string:concat(ROOT, "deps/riak_pb/ebin")),
		true = code:add_path(string:concat(ROOT, "ebin")),
		
		net_kernel:start([erlang:list_to_atom(string:concat("client",REGION)), longnames]),

		io:format("Arguments: ~p ~p ~p~n",[list_to_atom(SERVER_ADDRESS),N_THREADS, OUTPUT_DIR]),
		
		client_rc:init(list_to_atom(SERVER_ADDRESS), list_to_integer(N_THREADS), OUTPUT_DIR).
