#!/usr/local/bin/escript
%% -*- erlang -*-
%%! -smp enable -sname script -mnesia debug verbose

%%Addesses and ids must be acessible by indexes

main([LOCAL_ADDRESS,N_THREADS, ROOT, BUCKET, BUCKET_TYPE | _ ]) ->
		true = code:add_path(string:concat(ROOT, "deps/riakc/ebin")),
		true = code:add_path(string:concat(ROOT, "deps/meck/ebin")), 
		true = code:add_path(string:concat(ROOT, "deps/protobuffs/ebin")),
		true = code:add_path(string:concat(ROOT, "deps/riak_pb/ebin")),
		true = code:add_path(string:concat(ROOT, "ebin")),

        N = list_to_integer(N_THREADS),

		BUCKET_TERM = {list_to_binary(BUCKET_TYPE), list_to_binary(BUCKET)},
		
		MY_ID= string:sub_string(LOCAL_ADDRESS,1,string:rstr(LOCAL_ADDRESS,":")-1),
		MY_ADDRESS = string:sub_string(LOCAL_ADDRESS,string:rstr(LOCAL_ADDRESS,":")+1),
		
		io:format("Local Id: ~p.~n",[MY_ID]),
		%io:format("ALL Addresses: ~p~n",[[LOCAL_ADDRESS | OTHER_SERVER_ADDRESSES]]),

		client:init(N, MY_ADDRESS, BUCKET_TERM, MY_ID).
