#!/usr/local/bin/escript
%% -*- erlang -*-
%%! -smp enable -setcookie crdtdb

main([SERVER_ADDRESS,N_THREADS, N_KEYS,TOTAL_TIME, GENERATOR, DECREMENT_PROBABILITY, ROOT, OUTPUT_DIR, REGION]) ->

		true = code:add_path(string:concat(ROOT, "deps/riakc/ebin")),
		true = code:add_path(string:concat(ROOT, "deps/meck/ebin")), 
		true = code:add_path(string:concat(ROOT, "deps/protobuffs/ebin")),
		true = code:add_path(string:concat(ROOT, "deps/riak_pb/ebin")),
		true = code:add_path(string:concat(ROOT, "ebin")),

		net_kernel:start([erlang:list_to_atom(REGION), longnames]),

		Generator = list_to_atom(GENERATOR),
		NKeys = list_to_integer(N_KEYS),
        GeneratorPid = spawn_link(number_generator,Generator,[NKeys]),
		time_client_rc:init(list_to_atom(SERVER_ADDRESS),
		                    list_to_integer(N_THREADS),
                            GeneratorPid,
		                    list_to_integer(TOTAL_TIME),
		                    list_to_float(DECREMENT_PROBABILITY),
		                    OUTPUT_DIR,
                            REGION
                           ).
