#!/usr/local/bin/escript
%% -*- erlang -*-
%%! -smp enable -name client -setcookie crdtdb


%%Addesses and ids must be acessible by indexes

main([LOCAL_ADDRESS,N_THREADS, ROOT, OUTPUT_DIR]) ->
		true = code:add_path(string:concat(ROOT, "deps/riakc/ebin")),
		true = code:add_path(string:concat(ROOT, "deps/meck/ebin")), 
		true = code:add_path(string:concat(ROOT, "deps/protobuffs/ebin")),
		true = code:add_path(string:concat(ROOT, "deps/riak_pb/ebin")),
		true = code:add_path(string:concat(ROOT, "ebin")),

		Address = erlang:list_to_atom(string:sub_string(LOCAL_ADDRESS,string:rstr(LOCAL_ADDRESS,":")+1)),
		client_rc:init(Address, list_to_integer(N_THREADS), OUTPUT_DIR).
