#!/usr/local/bin/escript
%% -*- erlang -*-
%%! -smp enable -mnesia debug verbose

%%Addesses and ids must be acessible by indexes

main([RIAK_ADDRESS, RIAK_PORT, N_THREADS, ROOT, BUCKET, BUCKET_TYPE, REGION, FOLDER | _ ]) ->
		true = code:add_path(string:concat(ROOT, "deps/riakc/ebin")),
		true = code:add_path(string:concat(ROOT, "deps/meck/ebin")), 
		true = code:add_path(string:concat(ROOT, "deps/protobuffs/ebin")),
		true = code:add_path(string:concat(ROOT, "deps/riak_pb/ebin")),
		true = code:add_path(string:concat(ROOT, "ebin")),

		net_kernel:start([erlang:list_to_atom(string:concat("client",REGION)), longnames]),

       	BUCKET_TERM = {list_to_binary(BUCKET_TYPE), list_to_binary(BUCKET)},
		
		client_counter:init(RIAK_ADDRESS, list_to_integer(RIAK_PORT), list_to_integer(N_THREADS), BUCKET_TERM, FOLDER).
