#!/usr/local/bin/escript
%% -*- erlang -*-
%%! -smp enable -name client -setcookie crdtdb

main([NODE_ID_NAME,N_THREADS, N_KEYS,TOTAL_TIME, GENERATOR, DECREMENT_PROBABILITY, ROOT, OUTPUT_DIR]) ->

		true = code:add_path(string:concat(ROOT, "deps/riakc/ebin")),
		true = code:add_path(string:concat(ROOT, "deps/meck/ebin")), 
		true = code:add_path(string:concat(ROOT, "deps/protobuffs/ebin")),
		true = code:add_path(string:concat(ROOT, "deps/riak_pb/ebin")),
		true = code:add_path(string:concat(ROOT, "ebin")),

		Address = erlang:list_to_atom(string:sub_string(NODE_ID_NAME,string:rstr(NODE_ID_NAME,":")+1)),
		Generator = list_to_atom(GENERATOR),
		NKeys = list_to_integer(N_KEYS),
        GeneratorPid = spawn_link(number_generator,Generator,[NKeys,1]),
		time_client_rc:init(Address,
		                    list_to_integer(N_THREADS),
                            GeneratorPid,
		                    list_to_integer(TOTAL_TIME),
		                    list_to_float(DECREMENT_PROBABILITY),
		                    OUTPUT_DIR).
