#!/usr/local/bin/escript
%% -*- erlang -*-
%%! -smp enable -sname script -mnesia debug verbose

%%Addesses and ids must be acessible by indexes

main([RIAK_ADDRESS, RIAK_PORT, N_THREADS, ROOT, BUCKET, BUCKET_TYPE, FOLDER | _ ]) ->
		true = code:add_path(string:concat(ROOT, "deps/riakc/ebin")),
		true = code:add_path(string:concat(ROOT, "deps/meck/ebin")), 
		true = code:add_path(string:concat(ROOT, "deps/protobuffs/ebin")),
		true = code:add_path(string:concat(ROOT, "deps/riak_pb/ebin")),
		true = code:add_path(string:concat(ROOT, "ebin")),

       	BUCKET_TERM = {list_to_binary(BUCKET_TYPE), list_to_binary(BUCKET)},
		
		MY_ADDRESS = string:sub_string(RIAK_ADDRESS,string:rstr(RIAK_ADDRESS,":")+1),
		
		%io:format("ALL Addresses: ~p~n",[[LOCAL_ADDRESS | OTHER_SERVER_ADDRESSES]]),
                                                                                                                      w
		client_counter:init(MY_ADDRESS, list_to_integer(RIAK_PORT), list_to_integer(N_THREADS), BUCKET_TERM, FOLDER).
