#!/usr/local/bin/escript
%% -*- erlang -*-
%%! -smp enable -setcookie crdtdb

main([SERVER_ADDRESS,RIAK_PORT,BUCKET,BUCKET_TYPE,N_THREADS,N_KEYS,TOTAL_TIME,GENERATOR,DECREMENT_PROBABILITY,ROOT,OUTPUT_DIR,REGION]) ->

		true = code:add_path(string:concat(ROOT, "deps/riakc/ebin")),
		true = code:add_path(string:concat(ROOT, "deps/meck/ebin")), 
		true = code:add_path(string:concat(ROOT, "deps/protobuffs/ebin")),
		true = code:add_path(string:concat(ROOT, "deps/riak_pb/ebin")),
		true = code:add_path(string:concat(ROOT, "ebin")),

		net_kernel:start([erlang:list_to_atom(string:concat("client",REGION)), longnames]),

		Generator = list_to_atom(GENERATOR),
		NKeys = list_to_integer(N_KEYS),
        GeneratorPid = spawn_link(number_generator,Generator,[NKeys]),
       	BUCKET_TERM = {list_to_binary(BUCKET_TYPE), list_to_binary(BUCKET)},
		time_client_wc:init(list_to_atom(SERVER_ADDRESS), 
							list_to_integer(RIAK_PORT), 
							BUCKET_TERM,
							list_to_integer(N_THREADS),
                            GeneratorPid,
		                    list_to_integer(TOTAL_TIME),
		                    list_to_float(DECREMENT_PROBABILITY),
		                    OUTPUT_DIR).
