#! /bin/sh
#
# gen_dev dev4 vars.src vars
#
# Generate an overlay config for devNNN from vars.src and write to vars
#

NAME=$1
TEMPLATE=$2
VARFILE=$3

## Allocate 10 ports per node
##   .7 - http

NUMBER=${NAME##dev}
BASE=$((9000 + 10 * $NUMBER))
PB_BASE=$((10000 + 10 * $NUMBER))
WEBPORT=$(($BASE + 8))
HANDOFFPORT=$(($BASE + 9))
PBPORT=$((PB_BASE + 7))
NODENAME="crdtdb$NUMBER@127.0.0.1"

echo "Generating $NAME - node='$NODENAME' http=$WEBPORT handoff=$HANDOFFPORT pb=$PBPORT"
sed -e "s/@NODE@/$NODENAME/" \
    -e "s/@WEBPORT@/$WEBPORT/" \
    -e "s/@HANDOFFPORT@/$HANDOFFPORT/" \
    -e "s/@PBPORT@/$PBPORT/" < $TEMPLATE > $VARFILE
